### ISSUE TITLE
Bug ? when run python3 cln2inv.py 

### ISSUE THREAD

**Issue by TaihuLight** [gryan11/cln2inv#1]
+ Python 3.7
+ PyTorch1.5
When I run ``` python3 cln2inv.py ```, it gets the  error.

```
python3 cln2inv.py 
running entire benchmark, use python cln2inv.py <problem_number> to run single problem
Traceback (most recent call last):
  File "cln2inv.py", line 109, in <module>
    main()
  File "cln2inv.py", line 95, in main
    solved, inv_str, runtime = run_code2inv_problem(i)
  File "cln2inv.py", line 62, in run_code2inv_problem
    pname=problem_num)
  File "/home/chengzi/Documents/cln2inv/cln/cln_training.py", line 285, in build_train_cln
    torch.nn.utils.clip_grad_norm_(cln_model.parameters(), 0.01)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/utils/clip_grad.py", line 30, in clip_grad_norm_
    total_norm = torch.norm(torch.stack([torch.norm(p.grad.detach(), norm_type) for p in parameters]), norm_type)
RuntimeError: stack expects a non-empty TensorList
```
This arises from the fact that the return value of the function ```build_generic_template``` in template_gen.py is invalid? But, how to fix it?

**Comment by gryan11** [comment]
I just set up and ran the project on a new ubuntu 18.04 vm and did not see any errors.

If you are encountering errors I recommend using a new virtual environment and following the setup directions in the README.
